name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore PhotoShare.sln
      working-directory: ./PhotoShare
    - name: Build
      run: dotnet build PhotoShare.sln --no-restore
      working-directory: ./PhotoShare
    - name: Test
      run: dotnet test PhotoShare.sln --no-build --verbosity normal
      working-directory: ./PhotoShare
      
      
  deployment:
    runs-on: ubuntu-latest
    environment: buildcheck
    steps:
      - name: CheckBuild
